### ISSUE TITLE
Tutorial ?

### ISSUE THREAD

**Issue by Nastras** [meteyou/creality-k1#2]
Hello, I would like to use your files but need some help. You have written that you create a tutorial. Can you tell me when this is available?

Thanks a lot!

Regards
Nastras

**Comment by Nastras** [comment]
I found the tutorial. I noticed that this link doesn't work or the file in the repo is missing.

wget -q -O printer_params.cfg https://github.com/meteyou/creality-k1/raw/main/klipper/config/addons/printer_params.cfg

**Comment by Nastras** [comment]
I get the following error with the monraker section:

root@creality /usr/share [#] ./moonraker-env/bin/pip install -r ./moonraker-org/scripts/moonraker-requirements.txt
Collecting tornado==6.2.0
  Using cached tornado-6.2.tar.gz (504 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: pyserial==3.4 in /usr/lib/python3.8/site-packages (from -r ./moonraker-org/scripts/moonraker-requirements.txt (line 3)) (3.4)
Collecting pyserial-asyncio==0.6
  Using cached pyserial_asyncio-0.6-py3-none-any.whl (7.6 kB)
Collecting pillow==9.3.0
  Downloading Pillow-9.3.0.tar.gz (50.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 46.7/50.4 MB 1.8 MB/s eta 0:00:03
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 437, in _error_catcher
    yield
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 560, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 526, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 94, in read
    self.__buf.write(data)
  File "/usr/share/moonraker-env/lib/python3.8/tempfile.py", line 474, in func_wrapper
    return func(*args, **kwargs)
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 400, in run
    requirement_set = resolver.resolve(
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
    super().__init__(
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 536, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 166, in unpack_url
    file = get_http_url(
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_internal/network/download.py", line 147, in __call__
    for chunk in chunks:
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 621, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 586, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/share/moonraker-env/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 454, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
pip._vendor.urllib3.exceptions.ProtocolError: ("Connection broken: OSError(28, 'No space left on device')", OSError(28, 'No space left on device'))

**Comment by Nastras** [comment]
<img width="1154" alt="Bildschirmfoto 2023-09-03 um 20 09 46" src="https://github.com/meteyou/creality-k1/assets/27686185/c046f925-676a-4678-b536-22160b0e65b1">

**Comment by meteyou** [comment]
This is your error:
```
No space left on device
```

**Comment by Nastras** [comment]
Thanks for the tip. I somehow overlooked that.
